Разметка главной страницы
htmlacademy-htmlcss/1326685-technomart-29 pull request #2
Opened 2020-09-16 19:12 UTC by iAl1ve

2020-09-17 10:46 UTC, zavsievich requested changes
Очень хорошая и качественная работа, молодец!

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +      </section>
В догонку за комментарием с 78 по 88 строчки: вариант со списком и отдельным элементом секции для слайдера хорош по семантике, но имеет несколько проблем:
1. визуальный порядок элементов будет отличаться от порядка прохождения сайта с помощью клавиатуры (tab / shift + tab) -- это довольно серьёзная проблема, которую стоит избегать;
2. сложное позиционирование (это сделать возможно, но придётся немного поиграться с гридами);

ИМХО, каждый элемент тут можно обернуть просто в `<article>`, потому что можно считать, что каждый из этих маленьких элементиков -- самостоятельная единица контента, которую можно вставить в любое место страницы и его семантика сохранится.
К примеру, на любой странице этого сайта можно поместить плиточку со "скидка 50%"  или "доставкой".
А для перфораторов, думаю, можно спокойно использовать элемент `<section>`

**Статья по теме:**
https://css-tricks.com/how-to-section-your-html/

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +        </div>
Как ты считаешь, можно ли вместо div использовать header?
header -- вводная часть секционного элемента, которая вводит нас в секцию, если он используется внутри элементов `<section> | <article>`.

 Приведу пример на твите: у нас есть "шапка" (`<header>`) этого твитта: аватарка автора, его имя и ник в твиттере. Шапка как бы вводит нас в этот твит: показывает информацию о человеке, написавшем этот твит. Далее идёт контент этого твита, а после него идёт как бы "подвал" (`<footer>`): какая-то мета-информация о твите о дате создания, с какого приложения был создан твит, ну и сколько лайков/комментариев и репостов получил этот твит
Кстати, весь контент этого твита можно положить в `<article>` как самостоятельную неделимую часть контента, который можно вырвать из любого места и, вставив в любое другое, его смысл не потеряется

![изображение](https://user-images.githubusercontent.com/33816770/93457019-292a6700-f8e7-11ea-9a17-33472c7e4a91.png)

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +              <a href="#">В закладки</a>
я бы сделал добавление в закладки кнопкой, потому что после клика переход на другую страницу обычно не осуществляется

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +            <del>32500 р.</del>
по семантике лучше подойдёт `<s>`, ведь мы не удаляем цену вообще, мы просто показываем то, что старая цена больше недействительна
подробнее:
https://www.w3schools.com/tags/tag_s.asp

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +        <div>
header (см. коммент выше)

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +        <div>
обязательно ли оборачивать список в div?

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +            <li><a href="#">Доставка</a></li>
кажется, тут больше подходят кнопки
самое простое правило: используй ВСЕГДА кнопки, а если их не хватает и нужен переход куда-то, то ссылка

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +      </section>
также сюда следует добавить блоки "доставка" и "кредит": они скрыты в фигме, чтобы их увидеть, создай новый проект в фигме, скопируй весь дизайн себе и вставь в свой проект, тогда ты сможешь посмотреть скрытые слои
тоже самое и со слайдами в перфораторе и скрытыми модалками

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +      </section>
мне кажется, контакты также относятся к информации о компании, поэтому их можно положить внутрь секции о компании, ну и, значит заголовок "Контакты" будет уже третьего уровня

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +      </ul>
Можно реорганизовать структуру, чтобы сделать её более понятной:
сначала логотип техномарта, потом адрес, дальше навигация со списком внутри неё
Преимущества подхода:
1. визуальный порядок и порядок в разметке одинаковы;
2. у нас появляется полноценная навигация в футере;
3. проще стилизовать.

2020-09-17 10:46 UTC, zavsievich commented on index.html
> +          <h3 class="visually-hidden">Авторское право</h3>
у нас есть h3, но где-то потерялся h2
давай его найдём)

2020-09-17 10:50 UTC, iAl1ve commented on index.html
> +        </div>
Тоже была идея его использовать во второй раз, но был не уверен. Поэтому оставил тэг <address> только внизу. Поправлю

2020-09-17 11:02 UTC, iAl1ve commented on index.html
> +            <li><a href="#">Доставка</a></li>
Тут были сомнения, вроде может вести на страницу о доставке, но если смотреть в ТЗ то там назначение этого блока слайдер. А в слайдере да согласен, кнопки больше подходят

2020-09-17 11:27 UTC, iAl1ve commented on index.html
> +        <div>
я был не уверен как правильней будет тень сделать, в этих кнопках для слайдера. Думал потом станет видней

2020-09-17 13:37 UTC, iAl1ve commented on index.html
> +        </div>
Отличный пример. Да получается можно и в header за место дива их поместить (https://css-tricks.com/how-to-section-your-html/#what-goes-inside-headers). Секцию с популярными производителями также сделаю

2020-09-17 13:52 UTC, iAl1ve commented on index.html
> +      </section>
Открываешь глаза мне, спасибо ). Сделал эти блоки `<article>`. Слайдер оставил через `<section>`, а про его позиционирование , буду решать проблемы по мере поступления.

2020-09-17 14:03 UTC, iAl1ve commented on index.html
> +      </section>
Точно. Теперь добавил надеюсь все скрытые области.

2020-09-17 14:09 UTC, iAl1ve commented on index.html
> +      </ul>
Согласен, так удобней. Смотрел и описывал слева направо, а можно было по другому. Единственное навигацию судя по макету представляю почему-то из двух списков (из-за разных у них стилей).

2020-09-17 14:21 UTC, iAl1ve commented
Доработал, посмотри теперь пожалуйста все ли как надо.

2020-09-20 20:30 UTC, zavsievich requested changes
Отлично! Осталось поправить немного, и у нас появится ооочень качественная работа, так держать!

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +    <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
тут маленькая опечатка "материаловИ"

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +    </div>
В прошлый раз не подумал об этом:
у нас есть список слайдов как отдельных секций с заголовком, ссылкой, описанием
я бы делал список и внутри каждого элемента section с контентом

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +    </div>
@iAl1ve , ты не мог бы, пожалуйста, рассказать, для чего этот блок?

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +    <h3>Компания «Тexномарт»</h3>
обычно подзаголовок оформляется через p, давай "Компания Техномарт" сделаем абзацем
а можно ещё сильнее заморочиться и сделать по красоте вот так:
`<h2>Компания «Тexномарт» <span class="visually-hidden">о нас</span></h2>`

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +  </address>
br -- это бррррр
я бы использовал этот тег в очень редких случаях: эти случаи понятны сразу в некотрых моментах
всё остальное можно лучше через максимальную ширину и разные блоки: дизайнер может захотеть добавить ссылке подчёркивание, выделить её другим цветом или сделать адрес курсивом -- вот поэтому лучше использовать разные элементы сразу при написании кода, а br оставить на совсем крайний случай

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +</section>
оказывается, модалки на это дз не нужно было верстать: мой большой косяк, прошу прощения
ну, зато потом будет проще)

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +      <h2>Разработано —</h2>
является ли ссылка на разработчика сайта/дизайна настолько важной, чтобы вкладывать её в заголовок второго уровня?
лично я бы, наверное, это в заголовок не оборачивал, но если ты считаешь, что он тут нужен, то оставляй)

2020-09-20 20:30 UTC, zavsievich commented on index.html
> +      <img src="img/index-logo.svg" width="220" height="47" alt="Логотип интернет-магазина «Техномарт»">
оооооооооочень сильно смущает, что весь логотип у нас вставляется картинкой
наверное, я бы вырезал только буквы, а красную область вокруг делал с помощью стилей
а как ты считаешь и почему ты решил вырезать всю красную область?

2020-09-21 07:50 UTC, iAl1ve commented on index.html
> +    </div>
Ссылка там одна на двух слайдах, судя по макету. Но по идее она может/должна быть разная. Сделаю!

2020-09-21 08:08 UTC, iAl1ve commented on index.html
> +      <h2>Разработано —</h2>
Да вот тоже были сомнения, особенно для seo важности иерархии и информации в заголовках

2020-09-21 19:10 UTC, zavsievich requested changes
Ух, очень маленькие замечания, и то вроде как все идут с прошлой страницы, про которые я не сказал
молодец!

2020-09-21 19:10 UTC, zavsievich commented on catalog.html
> +  <title>Техномарт</title>
это уже не просто техномарт, а страница Каталог сайта техномарт :)

2020-09-21 19:10 UTC, zavsievich commented on catalog.html
> +    <a href="#!">Оформить заказ</a>
можно сделать списком

2020-09-21 19:10 UTC, zavsievich commented on catalog.html
> +    <i>Интернет-магазин  строительных материалов  и инструментов для ремонта</i>
нет, мне всё-таки не нравится тут `<i>`
что такое i -- это часть фразового контента контента, которая призвана, чтобы выделить что-то (https://www.w3.org/International/questions/qa-b-and-i-tags#detail)
тут у нас ничего не выделяется: просто курсивный текст
возможно, если это важный текст, его можно обернуть в тег `<strong>`, который покажет его важность
а можно просто положить в `<p>` и не париться сильно :)
НО ТОЧНО НЕ i, НЕТ!

2020-09-21 19:37 UTC, iAl1ve commented on catalog.html
> +    </li>
А не усложняем этим мы структуру ? Видел в чате похожее мнение оформления каталога через article - https://github.com/htmlacademy-htmlcss/1483111-nerds-29/pull/3#discussion_r487567659 .

2020-09-21 19:49 UTC, zavsievich commented on catalog.html
> +    </li>
к сожалению, не увидел там article, но могу попробовать отстоять список!
итак, пользователь со скринридером переходит на секцию и ему скринридер озвучивает: Заголовок второго уровня ПЕРФОРАТОРЫ. Список, 1500 элементов, первый из 1500 элементов
как только человек услышит, что тут 1500 элементов, он явно убежит с этого списка
если список не использовать, то придётся использовать дополнительные средства, чтобы показать, сколько же товаров найдено по нашей фильтрации
пагинация/вечная прокрутка/удаление уже пролиставшихся элементов -- это вопросы, которые должен решать дизайнер с бизнес-аналитиком, заказчиком, тим-лидом и тд
никто не будет (я надеюсь) пихать сразу 100500 элементов: обычно показывают какую-то часть, а потом подругажают следующую, ну и удаляют уже прокрученные
почему нужен article? потому что он уже во второй раз используется на второй странице, потому что это компонент/блок, который можно заюзать снова где угодно
мне не кажется, что мы тут переусложняем, даже наоборот, делаем очень просто
когда начнёшь добавлять классы, я тебе покажу, как работать с такими компонентами внутри разных секций

2020-09-21 20:12 UTC, iAl1ve commented on catalog.html
> +      </div>
Согласен и на главной странице тогда тоже

2020-09-22 07:41 UTC, merged