Стилизация главной страницы и страницы каталога
htmlacademy-htmlcss/1326685-technomart-29 pull request #3
Opened 2020-09-30 10:26 UTC by iAl1ve

2020-09-30 20:06 UTC, zavsievich requested changes
Как всегда, очень хорошая работа, которую можно улучшить 👍

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <a class="popular-header__button button" href="#!">Все популярные производители</a>
а вот и проблема: секция popular-products закончилась, а popular-header ещё тут 
А ЕЩЁЁЁЁ
секции popular-products и producer абсолютно одинаковы
так что тут спокойно можно их назвать как-нибудь типа .board и всё
board, board__header, board__list, board__item > card

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <h2 class="service__title service-title">Сервисы</h2>
зачем service-title?

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <ul class="service__list-buttons">
кажется, -buttons тут лишний

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <ul class="service__list-buttons">
кажется, -buttons тут лишний

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <ul class="service__list-buttons">
кажется, -buttons тут лишний

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <ul class="service__list-buttons">
кажется, -buttons тут лишний

2020-09-30 20:06 UTC, zavsievich commented on index.html
> +      <div class="service__slider-wrapper delivery">
а зачем здесь delivery?

2020-10-02 08:44 UTC, iAl1ve commented on catalog.html
> +    <div class="container">
Хм. Кажется я понял , я оставлял эту обертку чтобы фон темно-синий верхний был, а потом светлый. Но можно по идее такое же сделать только с помощью градиента для всего header

2020-10-02 08:55 UTC, iAl1ve commented on catalog.html
> +      <p class="header-contacts__adress">г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
Походу моя проблема, это мне хочется сделать четкую иерархию вложенности. Хотя по сути это один большой блок с его элементами и в БЭМе деревья одноуровневые/плоские

2020-10-02 09:13 UTC, iAl1ve commented on catalog.html
> +<main class="catalog">
Согласен. Тогда сделаю div с таким классом

2020-10-02 09:38 UTC, iAl1ve commented on catalog.html
> +        <article class="products-list__article">
Мда, замылился взгляд. Ты прав, это круто и будет очень удобно.

2020-10-02 10:47 UTC, iAl1ve commented on css/style.css
> +  height: 61px;
Я пока зря походу сюда размеры начал вписывать )

2020-10-02 10:51 UTC, iAl1ve commented on css/style.css
> +  padding-left: 22px;
Я решил, что они будут выравниваться по левому краю и как ты написал выше, если будет больше текста то у него будет одинаковая ширина без задания правого padding (и если уберем высоту, то элемент просто перенесется на следующую строчку). Ну и как говорится единый padding-right не указать из макета, так как он зависит от текста внутри.

2020-10-02 11:25 UTC, iAl1ve commented on index.html
> +      <div class="service__slider-wrapper delivery">
Согласен, не по БЭМу. Там потом изображения декоративное слайдера нужно будет добавлять

2020-10-04 14:09 UTC, zavsievich approved these changes
Отличная работа, молодец!

2020-10-04 14:09 UTC, zavsievich commented on css/style.css
> +  padding-left: 22px;
просто если не будет padding-right, текст некрасиво упрётся в край элемента -- вот так: текст|
а с отступом он не будет пряио у границы, представь, как бы выглядело, если бы слева не было отступа
если справа не задан отступ, сделай его таким же, как левый -- это можно применить ко всему и всегда

2020-10-04 14:10 UTC, merged