Сетка на гридах и доработка
htmlacademy-htmlcss/1326685-technomart-29 pull request #5
Opened 2020-10-22 09:58 UTC by iAl1ve

2020-10-24 13:19 UTC, zavsievich requested changes
Я был готов выдать тебе медальку за отличный код, но из-за переопределения контейнеров её ты получишь только в следующий раз :)

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.page-catalog .catalog__list {
двух классов в селекторе не может быть -- это противоречит всей идее БЭМа

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  width: 192px;
опасно

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  grid-template-columns: 1fr 1fr 1fr 1fr;
repeat(4, 1fr) выглядит явно красивее :)

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  grid-template-columns: 1fr 1fr 1fr 1fr ;
repeat(4, 1fr) выглядит явно красивее :)

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  display: grid;
элементы в строку: грид лишний

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  margin-bottom: 70px;
у марджинов есть одно свойство: схлопывание называется
чтобы во время разработки не думать об это, обычно делают у элементов либо только нижние, либо только верхние отступы. Выбирай тот вариант, который тебе больше нравится
Подробнее:
https://medium.com/@hisbvdis/%D0%B2%D1%81%D1%91-%D1%87%D1%82%D0%BE-%D0%B2%D0%B0%D0%BC-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D0%B7%D0%BD%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE-css-margin-4c9e175a65fb

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.services__content {
у тебя блок service, а тут services
два элемента в ряд: флекст подходит лучше

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.service .container {
Переопредение!!!
добавляй класс service__container и для него уже пиши стили

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.about .container {
Переопределение!!!!!!!!!!!!!!! 
about__container

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.about .container {
Тут также грид не нужен, намного лучше использовать флекс

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.footer .container {
ты уже знаешь, что я тут хочу сказать

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +.footer__meta .container {
и тут тоже

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
> +  display: grid;
грид излишен: флекс подходит лучше

2020-10-24 13:19 UTC, zavsievich commented on catalog.html
>      <ol class="catalog__breadcrumbs breadcrumbs">
визуальный порядок элементов должен соответствовать порядку элементов в разметке

2020-10-24 13:19 UTC, zavsievich commented on css/style.css
>  .pagination__btn--active {
что-то не похоже на то, что на дизайне))

2020-10-27 10:17 UTC, iAl1ve commented on css/style.css
> +.header__toolbar {
Согласен. Просто я планировал делать это в следующем задании, где флексы. Но тут уже не до порядка, нужно быстрее заканчивать.

2020-10-27 11:12 UTC, iAl1ve commented on css/style.css
> +  width: 121px;
Хм, я подбивал это размер 121px для первой кнопки как по макету. А чтобы кнопка не поехала, действительно нужно было поставить min-height: 45px;

2020-10-27 12:40 UTC, iAl1ve commented on css/style.css
> +  width: 192px;
Оно переносится вниз если переполнение. Или нужно чтобы расширялось, если больше текста ? Какие лучшие практики для таких случаев ? Поставил пока значит min-width

2020-10-27 12:56 UTC, iAl1ve commented on css/style.css
> +  display: grid;
Сделал с помощью флекса . А изначальную причину приводил выше, потому что просили в задании сначала гридом сделать ).

2020-10-27 13:01 UTC, iAl1ve commented on css/style.css
> +  margin-bottom: 70px;
Да, тут я перемудрил. Я обычно нижние использую, но забыл поставить заголовку нижний марджин, а тексту оба влепил :).

2020-10-27 13:06 UTC, iAl1ve commented on css/style.css
> +.service .container {
🤗

2020-10-27 13:14 UTC, iAl1ve commented on css/style.css
> +.footer .container {
Ага, запомнил теперь 🤗

2020-10-27 13:41 UTC, iAl1ve commented on css/style.css
> +  display: grid;
Переделал, размеры из макета перенес внутрь элементов

2020-10-27 13:43 UTC, iAl1ve commented on catalog.html
>      <ol class="catalog__breadcrumbs breadcrumbs">
Это откуда взята эта строчка ? Посмотрел в критерии, в ТЗ, а также в задании и не вижу. Тем более по структуре и seo правильно будет идти сначала заголовку, а потом уже хлебным крошкам. Пока оставил как есть.

2020-10-27 13:51 UTC, iAl1ve commented on css/style.css
>  .pagination__btn--active {
Ага, уже после ПР заметил, что цвет активного пункта не совпадает. А также еще заметил другие padding у последнего элемента

2020-10-29 12:36 UTC, zavsievich approved these changes
Хорошая работа, молодец

2020-10-29 12:36 UTC, zavsievich commented on css/style.css
> +  width: 121px;
нет, размеры обычно писать не нужно: всё делается через паддинги
единственное, иногда нужно поставить min-width, если по дизайну у кнопок с разным контентом одинаковая ширина

2020-10-29 17:04 UTC, merged